### ISSUE TITLE
Pipe operator '|' renders tons of space in a table

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#896] opened 2016-08-12 00:52 UTC
See the following tables:

https://stage.docs.microsoft.com/en-us/dotnet/articles/fsharp/fsharp-language-reference/symbol-and-operator-reference/index?branch=dend-fsharp-exp#table-of-symbols-and-operators

https://stage.docs.microsoft.com/en-us/dotnet/articles/fsharp/fsharp-language-reference/symbol-and-operator-reference/index?branch=dend-fsharp-exp#operator-precedence

/cc @chenkennt

**Comment by mairaw** [comment] 2016-08-12 01:26
I will close this issue by design. Markdown interprets the pipe as a new cell.

This SO question has a possible solution: http://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table/17320389#17320389

Or use the same solution you used on MSDN: https://raw.githubusercontent.com/Microsoft/visualfsharpdocs/live/docs/conceptual/symbol-and-operator-reference-%5Bfsharp%5D.md

**Closed by mairaw** 2016-08-12 01:26 UTC
Labels: bug
