### ISSUE TITLE
Error in C# getting started

### ISSUE THREAD

**Issue by devlo** [dotnet/core-docs#746] opened 2016-07-05 22:35 UTC
https://www.microsoft.com/net/tutorials/csharp/getting-started/classes-objects

It should be `value` instead of `newSpeed`

Current:

```
public class Speedometer
{
    private int _currentSpeed;
    public int CurrentSpeed
    {
        get
        {
            return _currentSpeed;
        }
        set 
        {
            if(newSpeed < 0) return;
            if(newSpeed > 120) return;
            
            // value is a keyword used in setters representing the new value
            _currentSpeed = value; 
        }
    }
}
```

Proper:

```

public class Speedometer
{
    private int _currentSpeed;
    public int CurrentSpeed
    {
        get
        {
            return _currentSpeed;
        }
        set 
        {
            if(value < 0) return;
            if(value > 120) return;
            
            // value is a keyword used in setters representing the new value
            _currentSpeed = value; 
        }
    }
}
```

**Comment by mairaw** [comment] 2016-07-05 23:03
@ardalis this issue is in the tutorials for the .NET site. Can you fix that?

/cc @shanselman @davidcsa

**Comment by ardalis** [comment] 2016-07-05 23:34
Yes, will follow up shortly.

**Comment by ardalis** [comment] 2016-07-06 01:58
I don't see an issue here. There are two examples, only one of which uses ``newSpeed``. The two examples listed in the issue here are, as far as I can see, identical. The listing in the lesson that refers to ``newSpeed`` is showing how one might update a field without using C#'s support for properties:

`public class Speedometer
{
    private int _currentSpeed;
    public int GetCurrentSpeed()
    {
        return _currentSpeed;
    }
    public void SetCurrentSpeed(int newSpeed)
    {
        if(newSpeed < 0) return;
        if(newSpeed > 120) return;
        
        _currentSpeed = newSpeed;
    }
}`

But this isn't what @devlo is showing in the issue description, so I'm not sure where the problem is.

In any case, you can close this issue @mairaw since this isn't the proper repo to track problems with these tutorials. 

Please open a new issue at https://github.com/dotnet/training-tutorials/issues if there is still a problem to be corrected. Thanks.

**Comment by mairaw** [comment] 2016-07-06 02:40
Thanks @ardalis! I see the issue reported fixed on the site. Good to know the right repo as well.

**Closed by mairaw** 2016-07-06 02:40 UTC
Labels: bug, external
