### ISSUE TITLE
Buttons in API reference have bad color contrast

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#262] opened 2016-02-18 21:14 UTC
The "View Source" and "Improve this Doc" buttons in API reference use purple text on dark blue background, which is very hard to read. Another color combination should be used instead.

Screenshot:
![](http://imgur.com/QfXinAo.png)

**Comment by mairaw** [comment] 2016-02-22 18:51
This seems to be a duplicate of issue #192

**Comment by svick** [comment] 2016-02-22 19:38
@mairaw You're right.

**Comment by svick** [comment] 2016-02-28 18:55
Reopening, since #192 was closed, but the issue wasn't fixed.

**Comment by mairaw** [comment] 2016-02-29 18:32
You're right @svick. @blackdwarf, there seems to be some pages with the old button still. See this [API page](http://dotnet.github.io/api/System.Threading.Tasks.ParallelOptions.html) for an example where we have the new one and the old one.

**Comment by blackdwarf** [comment] 2016-02-29 18:33
@mairaw saw them.

**Comment by blackdwarf** [comment] 2016-02-29 18:33
@svick the issue was 50% fixed. :)

**Comment by blackdwarf** [comment] 2016-03-01 05:49
@mairaw @svick this should be fixed in #312. The build should drop soon.

**Closed** 2016-03-01 06:06 UTC
Labels: bug
