### ISSUE TITLE
The page for the System.Resources namespace is missing from API reference

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#751] opened 2016-07-06 12:58 UTC
[The API reference index](https://docs.microsoft.com/en-us/dotnet/core/api/index) links to [the page for the namespace `System.Resources`](https://docs.microsoft.com/en-us/dotnet/core/api/system.resources), but that page does not exist ("The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.").

Pages for types inside that namespace, like [`ResourceManager`](https://docs.microsoft.com/en-us/dotnet/core/api/system.resources.resourcemanager) seem to be fine

**Comment by rpetrusha** [comment] 2016-07-06 17:11
@svick We don't have any details about the cause of this issue, but it's an engineering problem that's been addressed, and a fix should be available shortly. We're trying to get more information both about the cause and the timeline for deploying the fix.

**Comment by rpetrusha** [comment] 2016-07-20 16:31
@svick This is finally working. The Resources namespace page is now accessible both from the .NET Core API Reference namespace list in the TOC section on the left and from the list of namespace descriptions in the page itself. Closing this issue.

**Closed by rpetrusha** 2016-07-20 16:31 UTC
Labels: Area - API Reference, bug, external
