### ISSUE TITLE
Create content for "Development using Visual Studio Code"

### ISSUE THREAD

**Issue by tsolarin** [dotnet/core-docs#497] opened 2016-06-03 10:33 UTC
Issue tracking new topic at https://github.com/dotnet/core-docs/blob/master/docs/getting-started/devenv/using-visual-studio-code.md

**Comment by BillWagner** [comment] 2016-06-03 17:14
closed as a duplicate of #282 

@tsolarin Please join the conversation on that issue. If you'd like to contribute, please let us know.

**Closed by BillWagner** 2016-06-03 17:14 UTC
